merge r538-542,544-546,549-550,555-557,559:
- Implement backendbuild recovery functionality. This allows
to recover environments remotely via the Trac Admin area.

- Increase database text fields.
builds.buildlog from varchar(50) to varchar(100)
builds.wrkdir from varchar(50) to varchar(100)
builds.portname from varchar(50) to varchar(100)
buildqueue.description from varchar(255) to varchar(4096)

rptinderbox:
- For svn-full portstrees we cannot use our cleanroom
approch to delete tainted packages from the package
cache because this means we throw away our full package
cache after every build.
- Some packages like perl have multiple symlinks in
different categories that point to the package in
All. This caused dead symlinks so we check all
symlinks now and delete what points to the package.
- Supress output in recovery function

rpdd:
- Reduce locking on backend table to reduce lock
contention in steps 30/31. This helps a lot when
checkout takes very long and would block the whole
backend during that time.
- Increase URL variables to 512 byte because fields like portname
and wrkdir got increased too.
- Improve getpage() and downloadfile() and let them
unset all environment variables before doing a new
call.
- Improve status check in step 30 to have more precise
error messages.
- Fix a very nasty bug in Step71 that was observed after r555 which
cleaned up environment variables before each getpage() and downloadfile()
call. The effect was that BUILDSTATUS was empty and so all builds ended
in "finished" state.

redports-trac:
- Change default status when creating new backend or backendbuild
to a safe default.
- Improve and fix recovering backendbuilds
- Add internal backend and backendbuild page for external monitoring

diff --git a/branches/1.0/rptinderbox/rptinderbox b/branches/1.0/rptinderbox/rptinderbox
--- a/branches/1.0/rptinderbox/rptinderbox
+++ b/branches/1.0/rptinderbox/rptinderbox
@@ -146,7 +146,7 @@ clean()
         zfs destroy -R ${ZFSVOLUME}
     fi
 
-    if [ -f "${WRKBASE}/${BUILD}/.build" ]; then
+    if [ -f "${WRKBASE}/${BUILD}/.build" -a ! -z "${LASTPACKAGEDATE}" ]; then
         NEWPACKAGES=`cd ${TINDERBOX}/packages/${PORTSTREE}/All/ && find * -type f -newermt "${LASTPACKAGEDATE}" -print`
 
         for package in ${NEWPACKAGES}
@@ -155,13 +155,11 @@ clean()
         
             if [ ! -z "${CLEANROOM_MODE}" ]; then
                 if [ -d "${WRKBASE}/${BUILD}/ports/${PKGPORT}" ]; then
-                    rm ${TINDERBOX}/packages/${PORTSTREE}/${PKGPORT%${PKGPORT##*/}}/${package}
-                    rm ${TINDERBOX}/packages/${PORTSTREE}/All/${package}
+                    find -L ${TINDERBOX}/packages/${PORTSTREE} -samefile ${TINDERBOX}/packages/${PORTSTREE}/All/${package} | xargs rm
                 fi
             else
                 if [ "${PKGPORT}" = "${PORT}" ]; then
-                    rm ${TINDERBOX}/packages/${PORTSTREE}/${PKGPORT%${PKGPORT##*/}}/${package}
-                    rm ${TINDERBOX}/packages/${PORTSTREE}/All/${package}
+                    find -L ${TINDERBOX}/packages/${PORTSTREE} -samefile ${TINDERBOX}/packages/${PORTSTREE}/All/${package} | xargs rm
                 fi
             fi
         done
@@ -188,6 +186,52 @@ clean()
 
         ${TINDERBOX}/scripts/tc rmBuildPortsQueueEntry -i ${ID}
     done
+
+    return 0
+}
+
+recover()
+{
+    BUILD=$1
+    DBUSER=`cat ${TINDERBOX}/scripts/ds.ph | grep "DB_USER" | cut -d"'" -f2`
+    DBPASS=`cat ${TINDERBOX}/scripts/ds.ph | grep "DB_PASS" | cut -d"'" -f2`
+    DBHOST=`cat ${TINDERBOX}/scripts/ds.ph | grep "DB_HOST" | cut -d"'" -f2`
+    DBNAME=`cat ${TINDERBOX}/scripts/ds.ph | grep "DB_NAME" | cut -d"'" -f2`
+
+    if [ ! -z "${DBPASS}" ]; then
+        DBPASS="-p${DBPASS}"
+    fi
+
+    # reset build status in database to IDLE
+    mysql -u${DBUSER} ${DBPASS} -h ${DBHOST} -e "UPDATE builds SET build_status = \"IDLE\" WHERE build_name = \"${BUILD}\";" ${DBNAME} 2>/dev/null || return 1
+
+    # cleanup tinderbox locks
+    rm -f ${TINDERBOX}/builds/${BUILD}/lock
+    rm -f ${TINDERBOX}/builds/${BUILD}/tinderdlock
+
+
+    # cleanup tinderbox queue
+    for ENTRY in `${TINDERBOX}/scripts/tc listBuildPortsQueue -r | egrep ":${BUILD}:"`
+    do
+        QUEUEID=`echo ${ENTRY} | cut -d: -f1`
+        PORT=`echo ${ENTRY} | cut -d: -f4`
+
+        ${TINDERBOX}/scripts/tc rmBuildPortsQueueEntry -i ${QUEUEID}
+    done
+
+    # remove zfs snapshot
+    ZFSVOLUME=`printf "${ZFSROOT}" ${BUILD}`
+    if zfs list -t snapshot | grep "${ZFSVOLUME}" >/dev/null ; then
+        zfs destroy ${ZFSVOLUME}@work 2>/dev/null || return 1
+    fi
+
+    # unmount tmpfs
+    #while umount -f ${ZFSROOT}/tinderbox/${BUILD} 2>/dev/null ; do
+    #    sleep 1
+    #done
+
+    # remove 
+    rm -rf ${WRKBASE}/${BUILD} || return 1
 
     return 0
 }
@@ -234,8 +278,12 @@ build()
         return 1
     fi
 
-    # aktuellstes package von build merken
-    if [ -d "${TINDERBOX}/packages/${BUILD}/All" ]; then
+    # for svn-full repositories we cannot delete the package cache
+    if [ -L "${WRKBASE}/${BUILD}/ports" ]; then
+        LASTPACKAGE=""
+        LASTPACKAGEDATE=""
+    # determine most recent package in the cache
+    elif [ -d "${TINDERBOX}/packages/${BUILD}/All" ]; then
         LASTPACKAGE=`ls -tr ${TINDERBOX}/packages/${BUILD}/All | grep -v "Makefile" | tail -1`
         LASTPACKAGEDATE=`stat -f %m ${TINDERBOX}/packages/${BUILD}/All/${LASTPACKAGE}`
         LASTPACKAGEDATE=`date -r ${LASTPACKAGEDATE} "+%Y-%m-%d %H:%M:%S"`
@@ -412,6 +460,16 @@ case "$1" in
 ;;
 'clean')
     if clean "$2" 2>&1 ; then
+        echo "OK"
+        return 0
+    else
+        echo "ERROR"
+        return 1
+    fi
+    return $?
+;;
+'recover')
+    if recover "$2" 2>&1 ; then
         echo "OK"
         return 0
     else
