rp[watch|commit|fetch]pr: - Various fixes and improvements

diff --git a/scripts/rpcommitpr b/scripts/rpcommitpr
--- a/scripts/rpcommitpr
+++ b/scripts/rpcommitpr
@@ -7,6 +7,7 @@ SVNROOT=http://svn.beta.redports.org/${SVNUSER}
 PR=$1
 PATCH=$2
 PORT=$3
+SUBJECT=$4
 
 PORTSTREE=/usr/ports
 SCRIPTROOT=`pwd`
@@ -27,35 +28,37 @@ fi
 
 PORTCATEGORY=${PORT%${PORT##*/}}
 
-svn co --non-interactive ${SVNROOT} ${TMPDIR}/ports || exit 1
-
-if ls ${TMPDIR}/ports/* 2>/dev/null ; then
-   svn rm ${TMPDIR}/ports/* || exit 1
-
-   svn ci --non-interactive --username ${SVNUSER} --password ${SVNPASS} \
-          --message "Cleanup repository" ${TMPDIR}/ports || exit 1
-fi
-
 if [ -f "${TMPDIR}/${PR}.diff" ]; then
    if [ ! -d "${PORTSTREE}/${PORT}" ]; then
       echo "Port ${PORT} not found"
       exit 1
    fi
 
+   # checkout repository
+   svn co -q --non-interactive ${SVNROOT} ${TMPDIR}/ports || exit 1
+
+   # cleanup repository
+   if ls ${TMPDIR}/ports/* >/dev/null 2>&1 ; then
+      svn rm -q --non-interactive ${TMPDIR}/ports/* || exit 1
+
+      svn ci -q --non-interactive --username ${SVNUSER} --password ${SVNPASS} \
+             --message "Cleanup repository" ${TMPDIR}/ports || exit 1
+   fi
+
    # copy port from porstree to our svn repo
    mkdir -p ${TMPDIR}/ports/${PORT}
    cp -pR ${PORTSTREE}/${PORT}/ ${TMPDIR}/ports/${PORT}
-   svn add ${TMPDIR}/ports/*
+   svn add -q --non-interactive ${TMPDIR}/ports/* || exit 1
 
    echo "Add ${PORT}" > ${TMPDIR}/ci
    echo "" >> ${TMPDIR}/ci
    echo "Redports: ignore" >> ${TMPDIR}/ci
 
-   svn ci --non-interactive --username ${SVNUSER} --password ${SVNPASS} \
+   svn ci -q --non-interactive --username ${SVNUSER} --password ${SVNPASS} \
           --file ${TMPDIR}/ci ${TMPDIR}/ports || exit 1
 
    # apply user patch to our svn repo
-   cd ${TMPDIR}/ports && patch -p0 -us < ${TMPDIR}/${PR}.diff || exit 1
+   patch -d ${TMPDIR}/ports -t -p0 -us < ${TMPDIR}/${PR}.diff || exit 1
 
    # cleanup .orig files
    find ${TMPDIR}/ports -iname "*.orig" -exec rm {} \;
@@ -64,38 +67,56 @@ if [ -f "${TMPDIR}/${PR}.diff" ]; then
    find ${TMPDIR}/ports -size 0c -exec svn rm --force {} \;
    
    # commit our patched port
-   svn add --force ${TMPDIR}/ports/* || exit 1
+   svn add -q --non-interactive --force ${TMPDIR}/ports/* || exit 1
 
-   echo "Build ${PORT}" > ${TMPDIR}/ci
+   if [ -z "${SUBJECT}" ]; then
+      echo "${PORT}" > ${TMPDIR}/ci
+   else
+      echo "${PORT}:" > ${TMPDIR}/ci
+      echo "${SUBJECT}" >> ${TMPDIR}/ci
+   fi
    echo "" >> ${TMPDIR}/ci
-   echo "PR:	${PR}" >> ${TMPDIR}/ci
+   echo "PR:	ports/${PR}" >> ${TMPDIR}/ci
    
-   svn ci --non-interactive --username ${SVNUSER} --password ${SVNPASS} \
+   svn ci -q --non-interactive --username ${SVNUSER} --password ${SVNPASS} \
           --file ${TMPDIR}/ci ${TMPDIR}/ports || exit 1
 
-   rm -Rf ${TMPDIR}
-
 elif [ -f "${TMPDIR}/${PR}.sh" ]; then
+   # checkout repository
+   svn co -q --non-interactive ${SVNROOT} ${TMPDIR}/ports || exit 1
+
+   # cleanup repository
+   if ls ${TMPDIR}/ports/* >/dev/null 2>&1; then
+      svn rm -q --non-interactive ${TMPDIR}/ports/* || exit 1
+
+      svn ci -q --non-interactive --username ${SVNUSER} --password ${SVNPASS} \
+             --message "Cleanup repository" ${TMPDIR}/ports || exit 1
+   fi
+
    # extract shar script
    mkdir -p ${TMPDIR}/ports/${PORTCATEGORY}
    cd ${TMPDIR}/ports/${PORTCATEGORY}
    sh ${TMPDIR}/${PR}.sh || exit 1
 
    # commit our patched port
-   svn add ${TMPDIR}/ports/${PORTCATEGORY} || exit 1
+   svn add -q --non-interactive ${TMPDIR}/ports/${PORTCATEGORY} || exit 1
 
-   echo "Build ${PORT}" > ${TMPDIR}/ci
+   if [ -z "${SUBJECT}" ]; then
+      echo "${PORT}" > ${TMPDIR}/ci
+   else
+      echo "${PORT}:" > ${TMPDIR}/ci
+      echo "${SUBJECT}" >> ${TMPDIR}/ci
+   fi
    echo "" >> ${TMPDIR}/ci
-   echo "PR:	${PR}" >> ${TMPDIR}/ci
+   echo "PR:	ports/${PR}" >> ${TMPDIR}/ci
    
-   svn ci --non-interactive --username ${SVNUSER} --password ${SVNPASS} \
+   svn ci -q --non-interactive --username ${SVNUSER} --password ${SVNPASS} \
           --file ${TMPDIR}/ci ${TMPDIR}/ports || exit 1
 
-   rm -Rf ${TMPDIR}
-   
 else
-   echo "Invalid PR patch!"
-   exit 1
+   echo "PR does not have a patch"
 fi
+
+rm -Rf ${TMPDIR}
 
 exit 0
diff --git a/scripts/rpwatchpr b/scripts/rpwatchpr
--- a/scripts/rpwatchpr
+++ b/scripts/rpwatchpr
@@ -29,25 +29,33 @@ if [ "$1" = "update" ]; then
    fgrep "<td><a href='/cgi/query-pr.cgi?pr=" ${TMPPR} > ${THISPR}
 fi
 
-diff ${LASTPR} ${THISPR} | grep "^>" | head -n 5 | while read LINE
+diff ${LASTPR} ${THISPR} | grep "^>" | while read LINE
 do
    PR=`echo ${LINE} | cut -d'/' -f8 | cut -d"'" -f1`
    DATE=`echo ${LINE} | cut -d'>' -f6 | cut -d'<' -f1`
    SUBJECT=`echo ${LINE} | cut -d'>' -f14 | cut -d'<' -f1`
 
-   echo "-----------------------------------" >> ${PRDIR}/${PR}.log
-   echo `date` >> ${PRDIR}/${PR}.log
-   echo "PR:      ${PR}" >> ${PRDIR}/${PR}.log
-   echo "DATE:    ${DATE}" >> ${PRDIR}/${PR}.log
-   echo "SUBJECT: ${SUBJECT}" >> ${PRDIR}/${PR}.log
-   echo "" >> ${PRDIR}/${PR}.log
-   
-   ./rpcommitpr ${PR} >> ${PRDIR}/${PR}.log 2>&1
+   echo "-----------------------------------" | tee -a ${PRDIR}/${PR}.log
+   echo `date` | tee -a ${PRDIR}/${PR}.log
+   echo "PR:      ${PR}" | tee -a ${PRDIR}/${PR}.log
+   echo "DATE:    ${DATE}" | tee -a ${PRDIR}/${PR}.log
+   echo "SUBJECT: ${SUBJECT}" | tee -a ${PRDIR}/${PR}.log
+   echo "" | tee -a ${PRDIR}/${PR}.log
 
-   if [ $? -eq 0 ]; then
-      echo `date` ${DATE} ${PR} ${SUBJECT} >> ${LOGDIR}/success.log
+   if fgrep " ${PR} " ${LOGDIR}/success.log >/dev/null 2>&1 ; then
+      echo "PR already successfully scheduled. skipping"
+   elif [ `echo ${DATE} | cut -d'/' -f1` != "2012" ]; then
+      echo "PR too old. skipping"
    else
-      echo `date` ${DATE} ${PR} ${SUBJECT} >> ${LOGDIR}/failed.log
+      ./rpcommitpr "${PR}" "1" "" "${SUBJECT}" | tee -a ${PRDIR}/${PR}.log 2>&1
+
+      if [ $? -eq 0 ]; then
+         echo "success."
+         echo `date` ${DATE} ${PR} ${SUBJECT} >> ${LOGDIR}/success.log
+      else
+         echo "failed."
+         echo `date` ${DATE} ${PR} ${SUBJECT} >> ${LOGDIR}/failed.log
+      fi
    fi
 done
 
